# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Speedway < Formula
  desc ""
  homepage ""
  version "1.0.3-beta.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.1/speedway_1.0.3-beta.1_darwin_arm64.tar.gz"
      sha256 "55f62aa330f4ae12eb63032a4f2c527d21082e226aabb7f7cbfa84026234f268"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.1/speedway_1.0.3-beta.1_darwin_amd64.tar.gz"
      sha256 "940cb9399a8f11d1e63b6cc55b772d6cd7490e85c98caf2a30f90aee1d888c8a"

      def install
        bin.install "speedway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.1/speedway_1.0.3-beta.1_linux_arm64.tar.gz"
      sha256 "c9830d56ac06f61670162e50f8365e688122767b6bbf93892529e7a3fd97e928"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.1/speedway_1.0.3-beta.1_linux_amd64.tar.gz"
      sha256 "16588ff499291970d1e37b96499a82deb6e3e0d0492cc4fc9e83bf3c43d57f7e"

      def install
        bin.install "speedway"
      end
    end
  end
end
