# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Speedway < Formula
  desc ""
  homepage ""
  version "1.0.3-beta.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.3/speedway_1.0.3-beta.3_darwin_amd64.tar.gz"
      sha256 "6024bd6336466e7a7f6e7a1efb6b39bc52da975bcd1ff12bb3e2c3c3fbe8e39e"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.3/speedway_1.0.3-beta.3_darwin_arm64.tar.gz"
      sha256 "cffc18821c0452ee9a8baa8db475e7785ee91af1dc0b88460f3131f799efb8a9"

      def install
        bin.install "speedway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.3/speedway_1.0.3-beta.3_linux_arm64.tar.gz"
      sha256 "af61b1a06b7f652f7be65f2797a11c92f453ea8527deca26040208c1f3d5818a"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/v1.0.3-beta.3/speedway_1.0.3-beta.3_linux_amd64.tar.gz"
      sha256 "7dcc20525d48c3529c9fac393ffefe1f6f6e6a5c2c947c82d672a7b355ed8edf"

      def install
        bin.install "speedway"
      end
    end
  end
end
