# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Speedway < Formula
  desc ""
  homepage ""
  version "1.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/speedway/releases/download/v1.1.3/speedway_1.1.3_darwin_arm64.tar.gz"
      sha256 "12e16265d836ba1ece5e9d142cd198482e54f81f4e5509dcd17a022232293f6a"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/v1.1.3/speedway_1.1.3_darwin_amd64.tar.gz"
      sha256 "0af5c72835c8d63da8aeeb9a586af796ab67ab2b1750cc51b4b3003e17e6e3e1"

      def install
        bin.install "speedway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/speedway/releases/download/v1.1.3/speedway_1.1.3_linux_amd64.tar.gz"
      sha256 "2049070b1f0612a735c99dd92955b499e2a8f8db7d32b747eab9e82570dd2046"

      def install
        bin.install "speedway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonr-io/speedway/releases/download/v1.1.3/speedway_1.1.3_linux_arm64.tar.gz"
      sha256 "8048739102bb58b9052022f98b0e3497401a9723fa371d9ae987202df3e6b74b"

      def install
        bin.install "speedway"
      end
    end
  end
end
